import type { Product } from "./product-store"

export const mockProducts: Product[] = [
  {
    id: "PRD-1001",
    name: "Organic Cotton T-Shirt",
    sku: "IDR-TSHIRT-001",
    collection: "Summer Essentials",
    productType: "T-shirt",
    costPrice: 12.5,
    retailPrice: 39.99,
    margin: 69,
    status: "active",
    description: "Premium organic cotton t-shirt with sustainable manufacturing process.",
    quantity: 250,
    warehouse: "Paris",
    restockThreshold: 50,
    images: ["/placeholder.svg?height=300&width=300"],
    notes: [
      {
        id: "note-1",
        text: "Bestseller in previous collection. Consider expanding color options.",
        timestamp: new Date(2023, 5, 15),
        user: "Sarah Johnson",
      },
    ],
    tags: ["organic", "sustainable", "essentials"],
  },
  {
    id: "PRD-1002",
    name: "Recycled Denim Jeans",
    sku: "JEANS-002",
    collection: "Eco Collection",
    productType: "Pants",
    costPrice: 35.0,
    retailPrice: 129.99,
    margin: 73,
    status: "active",
    description: "Jeans made from recycled denim with modern slim fit.",
    quantity: 120,
    warehouse: "Berlin",
    restockThreshold: 30,
    images: ["/placeholder.svg?height=300&width=300"],
    notes: [
      {
        id: "note-2",
        text: "New supplier provides better quality. Check samples for next season.",
        timestamp: new Date(2023, 8, 20),
        user: "Emily White",
      },
    ],
    tags: ["recycled", "denim", "eco-friendly"],
  },
  {
    id: "PRD-1003",
    name: "Merino Wool Sweater",
    sku: "SWTR-003",
    collection: "Winter Collection",
    productType: "Sweatshirt",
    costPrice: 45.0,
    retailPrice: 159.99,
    margin: 72,
    status: "draft",
    description: "Premium merino wool sweater with ribbed collar and cuffs.",
    quantity: 0,
    warehouse: "Milan",
    restockThreshold: 25,
    images: ["/placeholder.svg?height=300&width=300"],
    notes: [
      {
        id: "note-3",
        text: "Waiting for final samples before production approval.",
        timestamp: new Date(2023, 11, 5),
        user: "David Lee",
      },
    ],
    tags: ["wool", "winter", "premium"],
  },
  {
    id: "PRD-1004",
    name: "Linen Blazer",
    sku: "BLZR-004",
    collection: "Summer Essentials",
    productType: "Jacket",
    costPrice: 65.0,
    retailPrice: 199.99,
    margin: 67,
    status: "active",
    description: "Lightweight linen blazer perfect for summer events.",
    quantity: 85,
    warehouse: "Paris",
    restockThreshold: 20,
    images: ["/placeholder.svg?height=300&width=300"],
    notes: [
      {
        id: "note-4",
        text: "Popular with 30-45 age demographic. Consider marketing focus.",
        timestamp: new Date(2024, 1, 10),
        user: "Alice Brown",
      },
    ],
    tags: ["linen", "summer", "formal"],
  },
  {
    id: "PRD-1005",
    name: "Silk Scarf",
    sku: "SCRF-005",
    collection: "Accessories",
    productType: "Accessory",
    costPrice: 18.0,
    retailPrice: 79.99,
    margin: 77,
    status: "active",
    description: "Hand-printed silk scarf with signature pattern.",
    quantity: 150,
    warehouse: "Milan",
    restockThreshold: 30,
    images: ["/placeholder.svg?height=300&width=300"],
    notes: [
      {
        id: "note-5",
        text: "Exclusive design for this season only.",
        timestamp: new Date(2024, 3, 1),
        user: "Bob Wilson",
      },
    ],
    tags: ["silk", "accessories", "limited"],
  },
  {
    id: "PRD-1006",
    name: "Leather Tote Bag",
    sku: "BAG-006",
    collection: "Accessories",
    productType: "Accessory",
    costPrice: 85.0,
    retailPrice: 299.99,
    margin: 72,
    status: "archived",
    description: "Handcrafted leather tote with brass hardware.",
    quantity: 0,
    warehouse: "Paris",
    restockThreshold: 15,
    images: ["/placeholder.svg?height=300&width=300"],
    notes: [
      {
        id: "note-6",
        text: "Discontinued due to supplier issues. Consider alternative for next season.",
        timestamp: new Date(2024, 4, 15),
        user: "Carol Davis",
      },
    ],
    tags: ["leather", "accessories", "discontinued"],
  },
  {
    id: "PRD-1007",
    name: "Cashmere Beanie",
    sku: "HAT-007",
    collection: "Winter Collection",
    productType: "Hat",
    costPrice: 25.0,
    retailPrice: 89.99,
    margin: 72,
    status: "active",
    description: "Soft cashmere beanie with ribbed texture.",
    quantity: 100,
    warehouse: "Berlin",
    restockThreshold: 25,
    images: ["/placeholder.svg?height=300&width=300"],
    notes: [
      {
        id: "note-7",
        text: "Consider expanding color range based on sales data.",
        timestamp: new Date(2024, 6, 20),
        user: "Ted Moore",
      },
    ],
    tags: ["cashmere", "winter", "accessories"],
  },
  {
    id: "PRD-1008",
    name: "Sustainable Sneakers",
    sku: "SHOE-008",
    collection: "Eco Collection",
    productType: "Footwear",
    costPrice: 40.0,
    retailPrice: 129.99,
    margin: 69,
    status: "draft",
    description: "Sneakers made from recycled ocean plastic and natural rubber.",
    quantity: 0,
    warehouse: "Berlin",
    restockThreshold: 40,
    images: ["/placeholder.svg?height=300&width=300"],
    notes: [
      {
        id: "note-8",
        text: "Waiting for certification before launch.",
        timestamp: new Date(2024, 7, 1),
        user: "Olivia Taylor",
      },
    ],
    tags: ["shoes", "sustainable", "eco-friendly"],
  },
  {
    id: "PRD-1009",
    name: "Bamboo Socks Set",
    sku: "SOCK-009",
    collection: "Essentials",
    productType: "Accessory",
    costPrice: 8.0,
    retailPrice: 29.99,
    margin: 73,
    status: "active",
    description: "Set of 3 pairs of bamboo fiber socks.",
    quantity: 300,
    warehouse: "Paris",
    restockThreshold: 60,
    images: ["/placeholder.svg?height=300&width=300"],
    notes: [
      {
        id: "note-9",
        text: "High-margin product with good repeat purchases.",
        timestamp: new Date(2024, 9, 10),
        user: "George Hall",
      },
    ],
    tags: ["bamboo", "essentials", "sustainable"],
  },
  {
    id: "PRD-1010",
    name: "Wool Overcoat",
    sku: "COAT-010",
    collection: "Winter Collection",
    productType: "Jacket",
    costPrice: 120.0,
    retailPrice: 399.99,
    margin: 70,
    status: "active",
    description: "Classic wool overcoat with satin lining.",
    quantity: 75,
    warehouse: "Milan",
    restockThreshold: 15,
    images: ["/placeholder.svg?height=300&width=300"],
    notes: [
      {
        id: "note-10",
        text: "Premium positioning has been successful. Maintain quality standards.",
        timestamp: new Date(2024, 10, 1),
        user: "Grace Clark",
      },
    ],
    tags: ["wool", "winter", "premium"],
  },
]

export const availableTags = [
  "organic",
  "sustainable",
  "essentials",
  "recycled",
  "denim",
  "eco-friendly",
  "wool",
  "winter",
  "premium",
  "linen",
  "summer",
  "formal",
  "silk",
  "accessories",
  "limited",
  "leather",
  "discontinued",
  "cashmere",
  "shoes",
  "bamboo",
]

export const collections = ["Summer Essentials", "Eco Collection", "Winter Collection", "Accessories", "Essentials"]

export const warehouses = ["Paris", "Berlin", "Milan"]

export const productTypes = [
  "T-shirt",
  "Hoodie",
  "Sweatshirt",
  "Jacket",
  "Pants",
  "Shorts",
  "Hat",
  "Accessory",
  "Footwear",
  "Other",
]
